name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Set Git identity
        run: |
          git config user.name "Aukasha"
          git config user.email "aukashakhan30@gmail.com"

      - name: Build and Deploy to GitHub Pages
        env:
          REPO: https://github.com/AukashaKhan/my-app.git
          TOKEN: ${{ secrets.deploy }}  # Personal access token from GitHub secrets
        run: |
          npm run build
          # Set git credentials
          git config --global user.name "Aukasha"
          git config --global user.email "aukashakhan30@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.deploy }}@github.com/AukashaKhan/my-app.git
          npx gh-pages -d build -r "https://x-access-token:${{ secrets.deploy }}@github.com/AukashaKhan/my-app.git"
